rewrite command of telescope
nvim-lua/telescope.nvim pull request #197
Opened 2020-10-27 12:12 UTC by glepnir

@tjdevries  now the usage like `Telescope find_files`. `Telescope grep_string`

current can't get theme option in viml, so does not support add theme option in command .

2020-10-27 12:26 UTC, tjdevries commented
Can we add a completion function for the first item at least? So that it can complete to the correct builtin?

2020-10-27 12:27 UTC, tjdevries commented
Also, do we want to leave the commands? I'm not sure if anyone is using them or not currently :/

2020-10-27 12:30 UTC, glepnir commented
we need command. because it's useful for some layload feature like dein.  use `on_cmd` keyword  of dein to load telescope.just load telescope when call the command.

2020-10-27 12:44 UTC, tjdevries commented
Sorry, I meant, do you want to leave the old commands you made? Or should we delete them.

2020-10-27 12:58 UTC, glepnir commented
yep we should delete. they are hardcored and sees ugly.. done.

2020-10-27 13:14 UTC, OkanEsen commented
This'll be a breaking change though and "seems" ugly is kind of subjective, no? :)

I think this change should be documented on the README at least or should probably throw an error, that the old commands are deprecated in favor of the new syntax?

2020-10-27 13:22 UTC, glepnir commented
Sorry for the impact on you, I didn’t consider more settings when I made them, so I rewrote them to make them more friendly.

If you use some lazyload plugin management like dein just config `on_cmd = 'Telescope'`,  And If you want  call them in commandline just ` Telescope ` then press `tab` .and support custom options of telescope

2020-10-27 13:27 UTC, OkanEsen commented
Don't be sorry, it's all good and doesn't affect me, since I use my own mappings likes this: 

``` lua
utils.gmap(
  "n",
  "xxx",
  [[<cmd>lua require'plugin.telescope'.foo_bar()<CR>]],
  {...}
)
```

I was just making a comment for the people this change could affect and that's why I suggested, that this change should probably be documented on the README. :)

2020-10-27 13:31 UTC, glepnir commented
The command is only effective for most people who use lazy loading. If load telescope normally, Just need to map `lua require`.

2020-10-27 13:58 UTC, tami5 commented
This is very useful change, I like it more then the previous way. Thanks @glepnir

2020-10-31 13:41 UTC, glepnir commented
@tjdevries cc/

2020-11-01 14:33 UTC, tjdevries commented
@glepnir can you add documentation to readme?

Also, for completion, you can use luaeval and vim.tbl_keys to get the keys, rather than hard coding. 

Then I will merge.

2020-11-01 14:52 UTC, glepnir commented
@tjdevries  Done.

2020-11-01 15:29 UTC, tjdevries requested changes
Small change, then it's good.

2020-11-01 15:29 UTC, tjdevries commented on plugin/telescope.vim
> +  let l:telescope_builtin = luaeval('require("telescope.builtin")')
In luaeval, you should just return the list of keys. I don't know that this table will always serialize.

Use vim.tbl_keys function.

2020-11-01 15:39 UTC, glepnir commented
Done. what about this?

2020-11-01 15:59 UTC, tjdevries commented
Sorry, I meant within the Lua eval call, inside the string.

I'm on mobile so it's too hard to type it at the moment 😂

2020-11-01 16:05 UTC, glepnir commented
@tjdevries  haha It's Ok. I know your means. Done.

2020-11-01 16:08 UTC, merged

2020-11-01 16:09 UTC, tjdevries commented
Thanks for fixing those things up! As always, thanks for the good ideas 😁